name: run test on pr
on: 
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for testing
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t testing-image --target=test .
      - name: Run docker image and upload to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          mkdir "${PWD}/coverage"
          chmod -R 777 "${PWD}/coverage"
          docker run \
          -v "${PWD}"/coverage:/opt/app/coverage \
          -i --rm testing-image npm test:coverage
          bash <(curl -s https://codecov.io/bash)
