name: run test on pr
on: 
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image for testing
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t testing-image --target=test .
      - name: Run docker image for testing
        run: |
          docker run testing-image npm test
